Catalogo
LudmilaBerto/TPF-e-commerce pull request #16
Opened 2024-09-05 20:27 UTC by ybamBogado

La mayoría de catalogo ya esta estilado

2024-09-05 20:38 UTC, LudmilaBerto requested changes
cambiar link de img por otro link funcional. y agregá un par de cards más

2024-09-05 23:35 UTC, ybamBogado commented
hola esta es la nueva pull request de catalogo

2024-09-07 02:23 UTC, LudmilaBerto commented
arregle algunas cosas, como las rutas que estaban mal especificadas en el header o al final de catalogo, eso es lo que estaba tirando error en la consola. Y pude sacar parte del html al principio del archivo catalogo.ejs y ahora toma los links que contiene el header

2024-09-07 02:30 UTC, LudmilaBerto commented
Hace el **git pull** antes de seguir trabajando sobre la rama. Faltaría el **Responsive** de la pagina. 

- Cada una de las cards, de los productos, deberían estar contenidas por una etiqueta <a> (etiqueta link) para que al hacer click en la card te dirija a la ruta de descripción-del-producto.

2024-09-08 03:05 UTC, ybamBogado commented
encerré las cards en etiquetas a

2024-09-08 03:08 UTC, closed without merging